### ISSUE TITLE
UI: dashboard detail page - "run on my OpenFaaS" button

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#171]
For the UI dashboard page I'd like to see a new button for users called "run on my OpenFaaS"

When you click on it a modal appears which you can copy/paste a stack.yml which is generated by the webpage using the Docker image name and function name.

It should also have a copy/paste command for the faas-cli to deploy.

Example:

Save as `stack.yml`:
```
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  octo:
    skip_build: true
    image: ofcommunity/alexellis-go-fns-tester-octo:latest-665d959
```

Then run: 

```
faas-cli deploy
```
