### ISSUE TITLE
UI: Dashboard add React metrics component

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#189]
## Expected Behaviour

Based upon #182 add a React.js component which renders metrics successful and errored for a function based upon the last hour or 24 hours (allow this to be a toggle in the UI.

Here is an example of what it could look like:

![img_20180918_182922](https://user-images.githubusercontent.com/6358735/45707848-d68f0680-bb77-11e8-943f-98822e771ce4.jpg)

Suggested fields:

```
Success req/s value / value %
Error req/s: value / value %
```

I.e.

```
Success req/s 800 / 80%
Error req/s: 200 / 20 %
```

**Comment by viveksyngh** [comment]
Derek add label: area/dashboard

**Comment by viveksyngh** [comment]
Derek add label: skill/beginner

**Comment by jaigouk** [comment]
I checked `https://hub.docker.com/u/functions/` and the system-metrics was not there.  so i changed my stack.yml

```yaml
system-metrics:
    lang: go
    handler: ./system-metrics
    image: jaigouk/system-metrics
    environment_file:
      - gateway_config.yml
    environment:
      content_type: "application/json"
```

```sh
faas-cli up --filter="system-metrics"
curl "http://127.0.0.1:31112/function/system-metrics?function=alexellis-figlet"
#=> returns {"success":0,"failure":0}
```
