### ISSUE TITLE
Give feedback via status when Secret not found

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#296]
## Expected Behaviour

OpenFaaS Cloud should give feedback via status when Secret not found

## Current Behaviour

I just saw a "400" error reported in the GitHub status, but have no idea what this means (as a user)

## Possible Solution

Give the error about the secret being missing for instance?

## Steps to Reproduce (for bugs)

1. Create a secret prefixed with your GitHub name i.e. alexellis-test-secret
2. Add `- test-secret` to `secrets:` (note no prefix here)
3. Push the code
4. See it work.
5. Edit to a name which doesn't exist
4. Check the GitHub checks UI for a vague error as above

**Comment by bartsmykla** [comment]
@alexellis I can't reproduce that issue. I have created secret `bartsmykla-test-secret` I have put it inside stack.yml of my function:
```
provider:
  name: faas
  gateway: ...

functions:
  go-fn:
    lang: go
    handler: ./go-fn
    image: bartsmykla/go-fn:0.0.0.1
    labels:
      com.openfaas.scale.min: 0
      com.openfaas.scale.max: 4
    secrets:
      - test-secret
```
and there is no information about missing secret anywhere.

Am I doing something wrong?
