### ISSUE TITLE
Apply Kubernetes NetworkPolicy to prevent accessing other functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#3]
We should apply a Kubernetes NetworkPolicy to prevent one user's functions accessing another's functions directly.

I.e. for an initial version the function should leave via egress and enter the public/private network IP of the gateway again if it wants to call another function.

Example:

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-gateway
  namespace: openfaas
spec:
  podSelector:
    matchLabels:
      app: gateway
  ingress:
  - from:
    - podSelector:
        matchLabels:
          namespace: openfaas-fn
```

Block access to the gateway app via pods in the openfaas-fn (functions) namespace.
